set XDG_DATA_HOME "$HOME/.local/share"
set XDG_CONFIG_HOME "$HOME/.config"
set XDG_STATE_HOME "$HOME/.local/state"
set XDG_CACHE_HOME "$HOME/.cache"

set XAUTHORITY "$XDG_RUNTIME_DIR/Xauthority"
set _JAVA_OPTIONS "-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
set CARGO_HOME "$XDG_DATA_HOME/cargo"
set WINEPREFIX "$XDG_DATA_HOME/wine"
set GNUPGHOME "$XDG_DATA_HOME/gnupg"
set CARGO_HOME "$XDG_DATA_HOME/cargo"
