#! /bin/sh

pkill sxhkd
sxhkd -c ~/.config/sxhkd/sxhkdrc-bspwm &
polybar &
feh Pictures/wallpapers/autumn.jpg --bg-fill --no-fehbg &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
#Gaps
GAPS=10
echo $GAPS > /tmp/bspwm-gaps.txt
bspc config window_gap $GAPS

bspc config focused_border_color "#77321A"
bspc config normal_border_color  "#260F07"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
